Bug fix missing resolveProperty method
Navigation property had no resolveProperty method. Copied from DataProperty.

TypeError: undefined is not a function
    at rootContext.displayName (http://localhost:12500/Scripts/breeze.debug.js:2021:41)
    at http://localhost:12500/Scripts/breeze.debug.js:2840:28
    at String.replace (native)
    at formatTemplate (http://localhost:12500/Scripts/breeze.debug.js:2831:25)
    at proto.getMessage (http://localhost:12500/Scripts/breeze.debug.js:2260:24)
    at proto.validate (http://localhost:12500/Scripts/breeze.debug.js:2230:71)
    at validate (http://localhost:12500/Scripts/breeze.debug.js:4183:28)
    at http://localhost:12500/Scripts/breeze.debug.js:4090:22
    at Array.forEach (native)
    at http://localhost:12500/Scripts/breeze.debug.js:4089:49